language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.5.*"

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install --dev

script:
  - bin/phpunit
